# libucontext Makefile.uk
#
# Authors: Maria Sfiraiala <maria.sfiraiala@gmail.com>
#
# Copyright (c) 2021, University Politehnica of Bucharest. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.


################################################################################
# Library registration
################################################################################
$(eval $(call addlib_s,libucontext,$(CONFIG_LIBUCONTEXT)))

################################################################################
# Original sources
################################################################################
LIBUCONTEXT_VERSION=1.3.2
LIBUCONTEXT_URL=https://github.com/kaniini/libucontext/archive/refs/tags/libucontext-$(LIBUCONTEXT_VERSION).tar.gz
LIBUCONTEXT_DIR=libucontext-libucontext-$(LIBUCONTEXT_VERSION)
LIBUCONTEXT_PATCHDIR=$(LIBUCONTEXT_BASE)/patches

$(eval $(call fetch,libucontext,$(LIBUCONTEXT_URL)))
$(eval $(call patch,libucontext,$(LIBUCONTEXT_PATCHDIR),$(LIBUCONTEXT_DIR)))

################################################################################
# Helpers
################################################################################
LIBUCONTEXT=$(LIBUCONTEXT_ORIGIN)/$(LIBUCONTEXT_DIR)

################################################################################
# Library includes
################################################################################
CINCLUDES-$(CONFIG_LIBUCONTEXT)   += -I$(LIBUCONTEXT)/include
CINCLUDES-$(CONFIG_LIBUCONTEXT)   += -I$(LIBUCONTEXT)/arch/common
CINCLUDES-$(CONFIG_LIBUCONTEXT)   += -I$(LIBUCONTEXT)/arch/common/include
CINCLUDES-$(CONFIG_ARCH_X86_64)   += -I$(LIBUCONTEXT)/arch/x86_64
CINCLUDES-$(CONFIG_ARCH_ARM_64)   += -I$(LIBUCONTEXT)/arch/aarch64

ASINCLUDES-$(CONFIG_LIBUCONTEXT)   += -I$(LIBUCONTEXT)/include
ASINCLUDES-$(CONFIG_LIBUCONTEXT)   += -I$(LIBUCONTEXT)/arch/common
ASINCLUDES-$(CONFIG_LIBUCONTEXT)   += -I$(LIBUCONTEXT)/arch/common/include
ASINCLUDES-$(CONFIG_ARCH_X86_64)   += -I$(LIBUCONTEXT)/arch/x86_64
ASINCLUDES-$(CONFIG_ARCH_ARM_64)   += -I$(LIBUCONTEXT)/arch/aarch64

################################################################################
# Global flags
################################################################################
# Suppress flags
LIBUCONTEXT_SUPPRESS_FLAGS += -Wno-unused-parameter \
	-Wno-unused-variable -Wno-unused-value -Wno-unused-function \
	-Wno-missing-field-initializers -Wno-implicit-fallthrough \
	-Wno-implicit-function-declaration
LIBUCONTEXT_CFLAGS-y   += $(LIBUCONTEXT_SUPPRESS_FLAGS) + -DEXPORT_UNPREFIXED

################################################################################
# Sources
################################################################################
LIBUCONTEXT_SRCS-$(CONFIG_LIBUCONTEXT)  += $(LIBUCONTEXT)/arch/common/common-trampoline.c

LIBUCONTEXT_SRCS-$(CONFIG_ARCH_X86_64)  += $(LIBUCONTEXT)/arch/x86_64/getcontext.S
LIBUCONTEXT_SRCS-$(CONFIG_ARCH_X86_64)  += $(LIBUCONTEXT)/arch/x86_64/makecontext.c
LIBUCONTEXT_SRCS-$(CONFIG_ARCH_X86_64)  += $(LIBUCONTEXT)/arch/x86_64/setcontext.S
LIBUCONTEXT_SRCS-$(CONFIG_ARCH_X86_64)  += $(LIBUCONTEXT)/arch/x86_64/swapcontext.S
LIBUCONTEXT_SRCS-$(CONFIG_ARCH_X86_64)  += $(LIBUCONTEXT)/arch/x86_64/trampoline.c

LIBUCONTEXT_SRCS-$(CONFIG_ARCH_ARM_64)  += $(LIBUCONTEXT)/arch/aarch64/getcontext.S
LIBUCONTEXT_SRCS-$(CONFIG_ARCH_ARM_64)  += $(LIBUCONTEXT)/arch/aarch64/makecontext.c
LIBUCONTEXT_SRCS-$(CONFIG_ARCH_ARM_64)  += $(LIBUCONTEXT)/arch/aarch64/setcontext.S
LIBUCONTEXT_SRCS-$(CONFIG_ARCH_ARM_64)  += $(LIBUCONTEXT)/arch/aarch64/swapcontext.S
LIBUCONTEXT_SRCS-$(CONFIG_ARCH_ARM_64)  += $(LIBUCONTEXT)/arch/aarch64/trampoline.c
